### ISSUE TITLE
Add filtering for folders

### ISSUE THREAD

**Issue by andyexpress** [kollivier/epub_viewer#1]
The filtering should also catch sub-folders, even though they won't be displayed by default unless the user clicks on their parent folder.

For example if there is a folder called "Warcraft" and inside it there is a folder called "Tales" and the user searches for "Tales" in the folder filtering bar, it should show the "Tales" folder - it doesn't matter that it's a sub-folder. But if the user searches for Warcraft, it should show the Warcraft folder. To view it's sub-folders, the user will have to click on it.

**Comment by kollivier** [comment]
Okay, I've implemented this. Please let me know if this works as expected for you.
